name: C/C++ CI

on:
  push:
    branches: [ "uat" ]
  pull_request:
    branches: [ "uat" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
